### ISSUE TITLE
sample in readme

### ISSUE THREAD

**Issue by hannesdelbeke** [BigRoy/usd-qtpy#11]
Hi

this sounds like an interesting project, 
as someone not familiar with USD, it would be helpfull to have an example of a tool in the readme.

**Comment by BigRoy** [comment]
Thanks @hannesdelbeke - I've just updated the readme through a recent PR I _just_ merged which shows some example code, however it does not include a thumbnail.

Does the current `README.md` already help you? or what are you missing to get started?

Note that this is just a first draft - there will be stuff broken as I'm continuing implementing things. It's early days really - I spent maybe at most a week or two on this so far. So a big **WIP** label should actually still be included.

**Comment by BigRoy** [comment]
![visual_with_custom_stylesheet](https://github.com/BigRoy/usd-qtpy/assets/2439881/feda9ce5-1e6e-4d7c-9e98-bdedfc4f1123)

For sake of reference - here's a screenshot for now with a custom stylesheet applied (roughly based on the one from [OpenPype](https://github.com/ynput/OpenPype)).

**Comment by BigRoy** [comment]
A screenshot is now in the readme in the main branch. Would you be expecting to see more there for now?

**Comment by hannesdelbeke** [comment]
looks good now
