### ISSUE TITLE
tree/simpletree.py still uses PySide2 as dependency instead of qtpy

### ISSUE THREAD

**Issue by Sasbom** [BigRoy/usd-qtpy#22]
https://github.com/BigRoy/usd-qtpy/blob/9c7f1ebe3cbc0b8a1ee6203ae4afc25b9090ccea/usd_qtpy/tree/simpletree.py#L3

Should be an easy fix, didn't want to make a branch for this one.

While editing this I also noticed that prim_spec_editor still uses PySide2.
https://github.com/BigRoy/usd-qtpy/blob/9c7f1ebe3cbc0b8a1ee6203ae4afc25b9090ccea/usd_qtpy/prim_spec_editor.py#L4

**Comment by BigRoy** [comment]
Thanks - I incorporated it in my current PR that I'm hoping to get through soon: https://github.com/BigRoy/usd-qtpy/pull/21
